<?php
#################################################################################
##                                                                             ##
##                                                                             ##
## --------------------------------------------------------------------------- ##
##                                                                             ##
##  Project:       TATAR WARS                                                  ##
##  Version:       2012.3.15                                                   ##
##  License:       Creative Commons BY-NC-SA 3.0                               ##
##  Copyright:     Bazaid (c) 2012 - All rights reserved                       ##
##  Source code:   https://github.com/Bazaid/tatar-wars                        ##
##                 http://sourceforge.net/projects/tatarwars/                  ##
#################################################################################

echo "﻿<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n";
$page = "http://localhost/dboorV4/register.php";
require( APP_PATH."config.php" );
if ( !( $link = mysql_connect( $AppConfig['db']['host'], $AppConfig['db']['user'], $AppConfig['db']['password'] ) ) )
{
    exit( mysql_error( ) );
}
if ( !mysql_select_db( $AppConfig['db']['database'], $link ) )
{
    exit( mysql_error( ) );
}
echo "يمكنك دعوة لاعب والحصول على ذهب عندما يبلغ عدد سكانه 100<br>عن طريق الرابط \r\nالتالي :<br>{$page}?ref=";
echo $this->myData['id'];
echo "<br><br>";
echo "<table id=\"plusFunctions\" cellpadding=\"1\" cellspacing=\"1\">";
echo "<thead>";
echo "<tr>";
echo "<th colspan=\"2\">لاعبين قمت بدعوتهم</th>";
echo "</tr>";
echo "<tr>";
echo "<td>اسم اللاعب</td>";
echo "<td>عدد السكان</td>";
echo "</tr>";
echo "</thead>";
echo "<tbody>";
$query = "select * from p_players";
$result = mysql_query( $query );
while ( $name = mysql_fetch_array( $result ) )
{
    if ( $name['invite'] == $this->myData['id'] )
    {
        echo "<tr><td><center>".$name['name']."</center></td><td><center>".$name['total_people_count']."</center></td></tr>";
        echo "</tbody>";
    }
    else
    {
        echo "<tr><td colspan=\\'2\\'><center>لم تقم بدعوة اي لاعب</center></td></tr></tbody>";
    }
    if ( $name['total_people_count'] == "100" && $name['is_invite'] == "0" )
    {
        mysql_query( "update `p_players` set `gold_num` = `gold_num`+ 100 where id='".$this->myData['id']."'" );
        mysql_query( "update `p_players` set `is_invite` = 1 where  id='".$this->myData['id']."'" );
    }
}
echo "</table>\r\n";
?>
