<?php
#################################################################################
##                                                                             ##
##                                                                             ##
## --------------------------------------------------------------------------- ##
##                                                                             ##
##  Project:       TATAR WARS                                                  ##
##  Version:       2012.3.15                                                   ##
##  License:       Creative Commons BY-NC-SA 3.0                               ##
##  Copyright:     Bazaid (c) 2012 - All rights reserved                       ##
##  Source code:   https://github.com/Bazaid/tatar-wars                        ##
##                 http://sourceforge.net/projects/tatarwars/                  ##
#################################################################################

require_once( LANG_UI_PATH."logout.php" );
echo "<h1>";
echo LANGUI_LOGOUT_T1;
echo "</h1>\r\n<img class=\"roman\" src=\"assets/x.gif\" alt=\"\">\r\n<p>";
echo LANGUI_LOGOUT_T2;
echo "</p>\r\n<p></p>\r\n\r\n<p>";
echo LANGUI_LOGOUT_T3;
echo "</p><br>\r\n<a href=\"index.php?dcookie\">";
echo LANGUI_LOGOUT_T4;
echo "</a>\r\n<p></p>";
?>
