<?php
#################################################################################
##                                                                             ##
##                                                                             ##
## --------------------------------------------------------------------------- ##
##                                                                             ##
##  Project:       TATAR WARS                                                  ##
##  Version:       2012.3.15                                                   ##
##  License:       Creative Commons BY-NC-SA 3.0                               ##
##  Copyright:     Bazaid (c) 2012 - All rights reserved                       ##
##  Source code:   https://github.com/Bazaid/tatar-wars                        ##
##                 http://sourceforge.net/projects/tatarwars/                  ##
#################################################################################

echo "<p class=\"f16\" align=\"center\">";
echo text_newvill_lang;
echo "</p>\r\n";
echo $this->getFlashContent( "assets/anm/war/nvil.swf", 500, 350 );
echo "<p class=\"f16\" align=\"center\"><a href=\"village1.php\">";
echo text_gotonext_lang;
echo "</a></p>";
?>
