<?php
#################################################################################
##                                                                             ##
##                                                                             ##
## --------------------------------------------------------------------------- ##
##                                                                             ##
##  Project:       TATAR WARS                                                  ##
##  Version:       2012.3.15                                                   ##
##  License:       Creative Commons BY-NC-SA 3.0                               ##
##  Copyright:     Bazaid (c) 2012 - All rights reserved                       ##
##  Source code:   https://github.com/Bazaid/tatar-wars                        ##
##                 http://sourceforge.net/projects/tatarwars/                  ##
#################################################################################

require_once( LANG_UI_PATH."footer.php" );
echo "<ul class=\"menu menu2\">\r\n\t<li><a href=\"index.php\">";
echo LANGUI_FOOTER_MAIN;
echo "</a></li>\r\n\t<li><a href=\"manual.php\">";
echo LANGUI_FOOTER_MANUAL;
echo "</a></li>\r\n\t<li><a href=\"training.php\">";
echo LANGUI_FOOTER_TRAINING;
echo "</a></li>\r\n\t<li><a href=\https://github.com/Bazaid/tatar-wars \" target=\"_blank\">Copyright &copy; To Bazaid </a></li>\r\n</ul>";
?>
